version: '3'
services:
  lne-posts:
    image: nouvelle0epoch/lne-posts
    env_file:
      - ./environment
    restart: always
    depends_on:
      - database
    ports:
      - 8081:8080
  database:
    image: postgres:10-alpine
    env_file:
      - ./environment
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - /home/ubuntu/posts/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    restart: always
volumes:
  postgres-data: {}