version: '3'
services:
  lne-posts:
    image: lne-posts-image
    env_file:
      - ./environment
    restart: always
    depends_on:
      - database
  database:
    image: postgres:10-alpine
    env_file:
      - ./environment
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: always
volumes:
  postgres-data: {}